### ISSUE TITLE
Code comments pls

### ISSUE THREAD

**Issue by AJLProjects** [AlexMulkerrin/PocketCiv#1]
Just comments on the methods about how they are used and what they do generally. I cant discern enough from the method/function names as is. But very good. I look forward to seeing the progress.

**Comment by AJLProjects** [comment]
TBH its a personal project so i'm just going to close this issue.

**Comment by AlexMulkerrin** [comment]
Once I move from the prototype phase and split classes into separate files there will be more documentation :)

**Comment by AlexMulkerrin** [comment]
Reopened because it is a valid issue. Proper codebase will have documentation!

**Comment by AlexMulkerrin** [comment]
All classes are now in separate source code files and fully commented :D
