### ISSUE TITLE
Start Development again

### ISSUE THREAD

**Issue by AlexMulkerrin** [AlexMulkerrin/PocketCiv#14]
It's been ages! D:

**Comment by spasquini** [comment]
Happy to hear that!

**Comment by AlexMulkerrin** [comment]
You'll be glad to know I'm picking up some seriously useful skills regarding software/game development at my new job :)

**Comment by spasquini** [comment]
I'm really glad for you!

**Comment by AlexMulkerrin** [comment]
Oh hey a commit (long train rides are always good for me getting back into coding :P )

**Comment by AlexMulkerrin** [comment]
been busy adding functionality to interface over past few days. Just about ready for a release :) I think that counts as having started development again!
