### ISSUE TITLE
Units disappear on water

### ISSUE THREAD

**Issue by spasquini** [AlexMulkerrin/PocketCiv#2]
When a unit tries to move into a water block, it disappears, together withj its "range of seeing". 
But the code is doing right, don't taking it like a finished move and waiting for a correct move.
Moving to a correct space, the unit appears again.
Probably it could be nice if the unit, when the user moves to a water block, shakes as to say "No, mate, not there!" then wait the correct move.

**Comment by AlexMulkerrin** [comment]
yep, a negative feedback would be great. I'll think about adding a red flash to the selection box, maybe a small 'denied' sound beep :)

**Comment by AlexMulkerrin** [comment]
Also I'll be revamping the faction vision map code. Current implementation is bad and creates several weird bugs D:

**Comment by AlexMulkerrin** [comment]
New faction vision map is in :D No longer do units lose sight during the turn!
