### ISSUE TITLE
Units disappear from time to time

### ISSUE THREAD

**Issue by spasquini** [AlexMulkerrin/PocketCiv#3]
When having a big number of units, in my case I had more than 15, and probably where they are near to each other, some of them disappear together with its "sight range".
When the turn for this invisible unit comes, the green square is there, correctly, with no unit visible. After the movement the unit turns out visible again.

**Comment by AlexMulkerrin** [comment]
Ah that faction vision map code has so many holes :o
Will fix asap

**Comment by AlexMulkerrin** [comment]
New faction vision map is in :D No longer do units lose sight during the turn!
