### ISSUE TITLE
Make the square border around the unit red for higher contrast to the mainly green environment

### ISSUE THREAD

**Issue by AJLProjects** [AlexMulkerrin/PocketCiv#5]
^^^

**Comment by AlexMulkerrin** [comment]
Maybe, green is a good colour for positive focus, red is more for warning.

I could see light blue or white working well too, will need to settle on an interface element palette first :)

**Comment by spasquini** [comment]
This green is working well, but maybe you could flash it a little when appearing, to catch player attention.

**Comment by AlexMulkerrin** [comment]
Selection highlight now animates.
