### ISSUE TITLE
Zero information about quality of city sites

### ISSUE THREAD

**Issue by AlexMulkerrin** [AlexMulkerrin/PocketCiv#7]
Player needs to know how productive a city will be before settling.

Also remove limit of how bad a tile can be before settling. The players demand their crappy cities I guess...

**Comment by spasquini** [comment]
Do you mean that each place on map has different "quality" for production purposes? Maybe they can be shown in the vertical bar aside ...

**Comment by AlexMulkerrin** [comment]
Yes, city information will be completely revamped, with details on the map underneath the sprite:
City name, production rate, bar showing progress to next unit and turns till complete :D

**Comment by AlexMulkerrin** [comment]
Side bar now gives info on current tile. Will recommend settling when on a good point but player is free to settle anywhere!*

*not in another city's territory, duh :P
