### ISSUE TITLE
Add 1000 turn limit 

### ISSUE THREAD

**Issue by AJLProjects** [AlexMulkerrin/PocketCiv#8]
just cos

**Comment by AlexMulkerrin** [comment]
actually turn limit for score purposes will be 500 turns :)

**Comment by spasquini** [comment]
Why to put a limit on turns? A game is finished when only one vic is still alive. Maybe you can also prompt the player if he/she wants to continue explore the world... or you can show the whole map, once dominated.

**Comment by AlexMulkerrin** [comment]
I agree 100% on not having a fixed turn limit :) The player should be allowed to continue to run a game as long as they please, even if their Civilisation has been defeated! :P

When the 500 turns have elapsed or the Player has won an earlier victory type they will be shown the victory screen: loads of stats and graphs of the game in it's entirety :3
They will have the option to watch an action replay of the entire history of the world, with or without being limited to their sight range.

Whole map vision is going to be a debug/cheat code that can be toggled at any time. Easy to implement :)

**Comment by AlexMulkerrin** [comment]
500 turn limit is now in for the latest in-development version :)
Will add option to continue playing after score screen
